name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: debug
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # cache: poetry
          # cache-dependency-path: "debug/poetry.lock"
        
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-path: "debug"
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/debug/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.cached-poetry-dependencies.outputs.cache-hit }}
          pwd
          echo ${{ github.workspace }}
          ls -a
          poetry install
